import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:uuid/uuid.dart';
import '../data/repositories/routine_repository.dart';
import '../../schedule/data/models/schedule_activity.dart';
import '../../schedule/data/repositories/schedule_repository.dart';

final routineSchedulerServiceProvider = Provider<RoutineSchedulerService>((ref) {
  return RoutineSchedulerService(
    ref.watch(routineRepositoryProvider),
    ref.watch(scheduleRepositoryProvider),
  );
});

class RoutineSchedulerService {
  final RoutineRepository _routineRepo;
  final ScheduleRepository _scheduleRepo;
  final Map<DateTime, Future<void>> _inFlight = {};

  RoutineSchedulerService(this._routineRepo, this._scheduleRepo);

  /// Generates missing schedule activities for a specific date based on active routines.
  /// Does not overwrite manually modified schedules or recreate deleted ones if tracked.
  Future<void> generateScheduleForDate(DateTime date) async {
    final key = DateTime(date.year, date.month, date.day);
    if (_inFlight.containsKey(key)) {
      await _inFlight[key];
      return;
    }

    final future = _generateScheduleForDateInternal(key);
    _inFlight[key] = future;
    try {
      await future;
    } finally {
      _inFlight.remove(key);
    }
  }

  Future<void> _generateScheduleForDateInternal(DateTime date) async {
    // 1. Get all active routines for this weekday
    // Phase 11 & 12: Guard routine generation by startDate, endDate, and frequency
    final allRoutines = await _routineRepo.getAllRoutines();
    final activeRoutines = allRoutines.where((r) => r.isActiveOn(date)).toList();
    
    if (activeRoutines.isEmpty) {
      return; // No active routine for this day
    }

    // 2. Get existing schedule activities for this date
    final existingActivities = await _scheduleRepo.getActivitiesForDate(date);
    
    final List<ScheduleActivity> newActivities = [];
    const uuid = Uuid();

    for (final routine in activeRoutines) {
      final blocks = await _routineRepo.getBlocksForRoutine(routine.id);
      for (var block in blocks) {
        if (!block.enabled) continue;

        // Check if a schedule activity already exists that was generated by this block
        final exists = existingActivities.any((a) => a.routineBlockId == block.id) ||
            newActivities.any((a) => a.routineBlockId == block.id);
        
        if (!exists) {
          // Generate new schedule activity from the block
          final startTime = DateTime(date.year, date.month, date.day, block.startTime.hour, block.startTime.minute);
          DateTime endTime;
          if (block.endTime.hour < block.startTime.hour ||
              (block.endTime.hour == 0 && block.endTime.minute == 0 && (block.startTime.hour > 0 || block.startTime.minute > 0))) {
            final nextDay = date.add(const Duration(days: 1));
            endTime = DateTime(nextDay.year, nextDay.month, nextDay.day, block.endTime.hour, block.endTime.minute);
          } else {
            endTime = DateTime(date.year, date.month, date.day, block.endTime.hour, block.endTime.minute);
          }
          
          newActivities.add(
            ScheduleActivity(
              id: uuid.v4(),
              title: block.title,
              description: block.description,
              date: date,
              startTime: startTime,
              endTime: endTime,
              category: block.category,
              icon: block.icon,
              color: block.color,
              notes: block.notes,
              routineBlockId: block.id,
              isOverridden: false,
              createdAt: DateTime.now(),
            )
          );
        }
      }
    }

    if (newActivities.isNotEmpty) {
      await _scheduleRepo.addActivities(newActivities);
    }
  }

  /// Cleans up schedule activities generated by a specific routine when it is deleted.
  Future<void> cleanupActivitiesForRoutine(String routineId) async {
    final blocks = await _routineRepo.getBlocksForRoutine(routineId);
    final blockIds = blocks.map((b) => b.id).toList();
    if (blockIds.isNotEmpty) {
      await _scheduleRepo.deleteActivitiesForRoutineBlockIds(blockIds);
    }
  }

  /// Cleans up schedule activities generated by a specific routine block when it is deleted.
  Future<void> cleanupActivitiesForBlock(String blockId) async {
    await _scheduleRepo.deleteActivitiesForRoutineBlockIds([blockId]);
  }
}
